### ISSUE TITLE
Some issue about Feature_extraction.py

### ISSUE THREAD

**Issue by dgh19940** [Madhav-Malhotra/cicIoT#2]
Hello,
In the script Feature_extraction.py, I encountered the same issue as you did while processing the original CIC-IoT pcap traffic. The issue arises in the section where the author performs a summary at the end of the script:
# summary
last_row = 0
n_rows = 10
df_summary_list = []
while last_row < len(processed_df):
    sliced_df = processed_df[last_row:last_row + n_rows]
    sliced_df = pd.DataFrame(sliced_df.mean()).T  # mean
    df_summary_list.append(sliced_df)
    last_row += n_rows

This code appears to compress every 10 rows of samples into one row in order to reduce the number of samples. I am not sure if this is feasible. Do you think there is a significant difference between the data after summarization and directly using:

processed_df = pd.DataFrame(base_row)
processed_df.to_csv(csv_file_name + ".csv", index=False)
attach my code, although it can run, I still feel that something is not right.
while last_row < len(processed_df):
    sliced_df = processed_df[last_row:last_row + n_rows]
    # select numeric_cols 
    numeric_cols = sliced_df.select_dtypes(include=[np.number])
    mean_df = pd.DataFrame(numeric_cols.mean()).transpose()
    df_summary_list.append(mean_df)
    last_row += n_rows

**Comment by Madhav-Malhotra** [comment]
RE: "Do you think there is a significant difference between the data after summarization and directly using [the raw data]"
The primary concern is that you'll just have a lot more data to deal with, which will make training on cloud platforms more difficult as you may not be able to load the entire dataset into memory for cheaper machines. 

A secondary concern is that the lack of averaging will make the data have more outliers. I found it difficult to get good training on data with outliers, so I [removed outliers with the DBSCAN method](https://www.kaggle.com/code/madhavmalhotra/unsupervised-clustering-and-negative-selection#DBSCAN)

**Comment by dgh19940** [comment]
> RE: "Do you think there is a significant difference between the data after summarization and directly using [the raw data]" The primary concern is that you'll just have a lot more data to deal with, which will make training on cloud platforms more difficult as you may not be able to load the entire dataset into memory for cheaper machines.
> 
> A secondary concern is that the lack of averaging will make the data have more outliers. I found it difficult to get good training on data with outliers, so I [removed outliers with the DBSCAN method](https://www.kaggle.com/code/madhavmalhotra/unsupervised-clustering-and-negative-selection#DBSCAN)



Thank you for your response. I found the original pcap packets from CIC-IoT-2023 to be quite redundant. I used the CICFlowMeter, previously proposed by the CIC Lab, to obtain csv files with features and conducted random sampling to minimize the number of samples as much as possible. I look forward to your continued work!
